#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
scratch="$(mktemp -d)"
trap 'rm -rf "${scratch}"' EXIT
source_repo="${scratch}/source"
target_repo="${scratch}/target"
mkdir -p "${source_repo}/catalog" "${source_repo}/modules" \
  "${source_repo}/profiles" "${target_repo}"

printf '%s\n' \
  '{"schema":"runtime-env/variables/v1","variables":[{"name":"OLLAMA_URL","secret":false,"description":"Ollama service root."}]}' \
  > "${source_repo}/catalog/variables.json"
printf '%s\n' \
  '{"schema":"runtime-env/module/v1","id":"ollama-root","summary":"Fixture.","requires":[],"optional":["OLLAMA_URL"],"defaults":{"OLLAMA_URL":"http://localhost:11434"}}' \
  > "${source_repo}/modules/ollama-root.json"
printf '%s\n' \
  '{"schema":"runtime-env/profile/v1","id":"bettor-arena-local","summary":"Fixture.","modules":["ollama-root"]}' \
  > "${source_repo}/profiles/bettor-arena-local.json"

git -C "${source_repo}" init -q
git -C "${source_repo}" config user.name fixture
git -C "${source_repo}" config user.email fixture@example.invalid
git -C "${source_repo}" add .
git -C "${source_repo}" commit -qm 'fixture source'
git -C "${source_repo}" remote add origin git@github.com:ed3c/runtime-env.git
git -C "${target_repo}" init -q

dry_output="$(${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}")"
[[ "${dry_output}" == *'WOULD-CREATE .runtime-env/bindings/bettor-arena-local.json'* ]]
[[ "${dry_output}" == *'WOULD-CREATE .runtime-env/examples/bettor-arena-local.env.example'* ]]
[[ ! -e "${target_repo}/.runtime-env" ]] || {
  echo "FAIL: dry-run wrote target files" >&2
  exit 1
}

${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --apply >/dev/null

binding="${target_repo}/.runtime-env/bindings/bettor-arena-local.json"
example="${target_repo}/.runtime-env/examples/bettor-arena-local.env.example"
[[ -f "${binding}" && -f "${example}" ]]
python3 - "${binding}" \
  "$(git -C "${source_repo}" rev-parse HEAD)" \
  "$(git -C "${source_repo}" rev-parse 'HEAD^{tree}')" <<'PY'
import json
from pathlib import Path
import sys

document = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
assert document["source"]["repository"] == "https://github.com/ed3c/runtime-env"
assert document["profile"] == "bettor-arena-local"
assert document["source"]["commit"] == sys.argv[2]
assert document["source"]["tree"] == sys.argv[3]
PY
[[ "$(cat "${example}")" == $'# Generated by runtime-env. Values are placeholders, never credentials.\n# optional; non-secret: Ollama service root.\nOLLAMA_URL=http://localhost:11434' ]]
if grep -Fq "${scratch}" "${binding}" "${example}"; then
  echo "FAIL: synchronized artifacts contain a local absolute path" >&2
  exit 1
fi

${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --check >/dev/null

printf '\n# local drift\n' >> "${example}"
before_check="$(shasum -a 256 "${example}" | awk '{print $1}')"
set +e
check_output="$(${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --check 2>&1)"
check_status=$?
set -e
[[ ${check_status} -eq 2 ]]
[[ "${check_output}" == *'DRIFT .runtime-env/examples/bettor-arena-local.env.example'* ]]
[[ "$(shasum -a 256 "${example}" | awk '{print $1}')" == "${before_check}" ]] || {
  echo "FAIL: sync --check mutated a drifted artifact" >&2
  exit 1
}

${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --apply >/dev/null
${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --check >/dev/null

printf '\n' >> "${source_repo}/profiles/bettor-arena-local.json"
set +e
dirty_output="$(${ROOT}/runtime-env --catalog-root "${source_repo}" sync \
  --profile bettor-arena-local --binding bettor-arena-local \
  --target-root "${target_repo}" --apply 2>&1)"
dirty_status=$?
set -e
[[ ${dirty_status} -eq 2 ]]
[[ "${dirty_output}" == *'catalog repository must be clean'* ]]

echo "PASS: explicit runtime-env sync dry-run, apply, and read-only drift check"
